version: '3.8'

services:
    #1. PostgreSQL
    postgres-db:
        image: postgres:15-alpine
        container_name: financial_postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgresadmin
            - POSTGRES_PASSWORD=Adm1nP@ssw0rd
            - POSTGRES_DB=FinancialPlatformDb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        
    #2. MongoDB
    mongodb:
        image: mongo:latest
        container_name: financial_mongodb
        command: mongod --auth
        ports:
            - "27018:27017"
        environment:
            - MONGO_INITDB_ROOR_USERNAME=mongoadmin
            - MONGO_INITDB_ROOR_PASSWORD=M0ngoAdm1n
        volumes:
            - mongodb_data_v2:/data/db
        restart: unless-stopped
        
    #3. Redis Cache
    redis-cache:
        image: redis:alpine
        container_name: financial_redis
        ports: 
            - "6379:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
        
    #4. Rabbit MQ
    rabitmq:
        image: rabbitmq:3-management-alpine
        container_name: financial_rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - rabbitmq_data:/var/lib/rabbitmq
        restart: unless-stopped
        
# volumes
volumes:
    postgres_data:
    mongodb_data_v2:
    redis_data:
    rabbitmq_data: